In [28]:
using Plots
N = 100
dv = zeros(N)
dx = 0.01
x = [(i-1)*dx for i in 1:N]

100-element Vector{Float64}:
 0.0
 0.01
 0.02
 0.03
 0.04
 0.05
 0.06
 0.07
 0.08
 0.09
 ⋮
 0.91
 0.92
 0.93
 0.9400000000000001
 0.9500000000000001
 0.96
 0.97
 0.98
 0.99

In [6]:
include("aux_functions_vlasov.jl")

thermal_rel_dist

In [23]:
par_Dx = (N, dx, dv)
D2x_Per(sin.(2π * x),par_Dx) - 2π*cos.(2π * x)
dv

100-element Vector{Float64}:
 6.279051952931332
 6.266661678215213
 6.229539752820561
 6.1678326800275265
 6.081783989461139
 5.971733275991156
 5.838114859506266
 5.68145607085187
 5.5023751706961965
 5.3015789095378905
 ⋮
 5.301578909537902
 5.502375170696205
 5.681456070851873
 5.83811485950623
 5.9717332759911255
 6.0817839894611465
 6.167832680027535
 6.229539752820571
 6.2666616782152325

In [29]:
S = reshape(x, 20, 5)

20×5 Matrix{Float64}:
 0.0   0.2   0.4   0.6   0.8
 0.01  0.21  0.41  0.61  0.81
 0.02  0.22  0.42  0.62  0.82
 0.03  0.23  0.43  0.63  0.83
 0.04  0.24  0.44  0.64  0.84
 0.05  0.25  0.45  0.65  0.85
 0.06  0.26  0.46  0.66  0.86
 0.07  0.27  0.47  0.67  0.87
 0.08  0.28  0.48  0.68  0.88
 0.09  0.29  0.49  0.69  0.89
 0.1   0.3   0.5   0.7   0.9
 0.11  0.31  0.51  0.71  0.91
 0.12  0.32  0.52  0.72  0.92
 0.13  0.33  0.53  0.73  0.93
 0.14  0.34  0.54  0.74  0.94
 0.15  0.35  0.55  0.75  0.95
 0.16  0.36  0.56  0.76  0.96
 0.17  0.37  0.57  0.77  0.97
 0.18  0.38  0.58  0.78  0.98
 0.19  0.39  0.59  0.79  0.99

In [30]:
S[:,2]

20-element Vector{Float64}:
 0.2
 0.21
 0.22
 0.23
 0.24
 0.25
 0.26
 0.27
 0.28
 0.29
 0.3
 0.31
 0.32
 0.33
 0.34
 0.35000000000000003
 0.36
 0.37
 0.38
 0.39

In [27]:
x

100-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 ⋮
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0